#!/usr/bin/env node
// convert-levels.mjs - turn frozenjs/minigolf's levelData.js into our Lua
// level table.
//
// WHY A CONVERTER AND NOT A HAND PORT: the original's 22 holes are already
// clean collision GEOMETRY -- 204 rectangles, 132 polygons, 95 circles with
// flags for water, sand and impulse zones. The holeN.png files are only
// backdrops; none of the collision comes from them. So the level DESIGNS
// port exactly, and re-typing 431 entities by hand would introduce errors
// a converter cannot make.
//
// Run once, commit the output. Re-run only if the source levels change.
//
//   node tools/convert-levels.mjs path/to/minigolf/src/levelData.js
//
// Source: https://github.com/frozenjs/minigolf (MIT, Iced Development LLC)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const src = process.argv[2];
if (!src) {
  console.error("usage: convert-levels.mjs <levelData.js>");
  process.exit(1);
}

// ── geometry ─────────────────────────────────────────────────────────
//
// The source course is 1500x1000; the cart is 1920x1080. A UNIFORM scale
// of exactly 1.0 fits it with 210px of gutter each side and 40px top and
// bottom -- which is both the cleanest possible conversion (no float
// scaling of any coordinate) and the shooting room the drag-back aim
// needs. Anything larger would push the ball against the screen edge on
// holes that start near a wall.
const SRC_W = 1500, SRC_H = 1000;
const DST_W = 1920, DST_H = 1080;
const SCALE = 1.0;
const OX = (DST_W - SRC_W * SCALE) / 2;   // 210
const OY = (DST_H - SRC_H * SCALE) / 2;   // 40

const tx = (x) => +(x * SCALE + OX).toFixed(2);
const ty = (y) => +(y * SCALE + OY).toFixed(2);
const tl = (v) => +(v * SCALE).toFixed(2);   // a length, not a position

// ── extract the JSON out of the AMD module ───────────────────────────
let s = readFileSync(src, "utf8");
const i = s.indexOf("var levels = [");
const j = s.indexOf("\n  ];", i);
if (i < 0 || j < 0) {
  console.error("could not find the levels array in " + src);
  process.exit(1);
}
let arr = s.slice(i + "var levels = ".length, j + 4).trim();
arr = arr.replace(/^\s*\/\/.*$/gm, "");     // strip the // Level N comments
const levels = JSON.parse(arr);

// ── emit ─────────────────────────────────────────────────────────────

const lua = [];
lua.push("-- levels.lua - GENERATED by tools/convert-levels.mjs. Do not hand-edit.");
lua.push("--");
lua.push("-- The 22 hole layouts from frozenjs/minigolf (MIT, Iced Development");
lua.push("-- LLC), converted from its levelData.js. Collision geometry only --");
lua.push("-- the original's backdrop PNGs are not used; this game draws the");
lua.push("-- course procedurally from these same shapes.");
lua.push("--");
lua.push(`-- Source course is ${SRC_W}x${SRC_H}; the cart is ${DST_W}x${DST_H}. Scale is`);
lua.push(`-- exactly ${SCALE}, offset (${OX}, ${OY}), so every coordinate stays a clean`);
lua.push("-- number and the gutter is the room the drag-back aim needs.");
lua.push("");
lua.push("return {");

const fmt = (n) => (Number.isInteger(n) ? String(n) : String(n));

let stats = { rect: 0, circle: 0, poly: 0, water: 0, sand: 0, zone: 0, joints: 0 };

levels.forEach((L, idx) => {
  lua.push(`  { -- hole ${idx + 1}`);
  lua.push("    entities = {");
  for (const e of L.entities) {
    const parts = [];
    parts.push(`id = ${typeof e.id === "string" ? `"${e.id}"` : `"e${e.id}"`}`);
    parts.push(`x = ${fmt(tx(e.x))}`, `y = ${fmt(ty(e.y))}`);

    if (e.type === "Rectangle") {
      parts.push(`kind = "rect"`);
      parts.push(`hw = ${fmt(tl(e.halfWidth))}`, `hh = ${fmt(tl(e.halfHeight))}`);
      stats.rect++;
    } else if (e.type === "Circle") {
      parts.push(`kind = "circle"`, `r = ${fmt(tl(e.radius))}`);
      stats.circle++;
    } else if (e.type === "Polygon") {
      parts.push(`kind = "poly"`);
      const pts = e.points.map((p) => `${fmt(tl(p.x))}, ${fmt(tl(p.y))}`).join(", ");
      parts.push(`points = { ${pts} }`);
      stats.poly++;
    } else {
      continue;   // unknown shape: skip rather than emit something wrong
    }

    if (e.staticBody === false) parts.push("dynamic = true");
    if (e.sensor) parts.push("sensor = true");
    if (e.water) { parts.push("water = true"); stats.water++; }
    if (e.sand) { parts.push("sand = true"); stats.sand++; }
    if (e.safe) parts.push("safe = true");
    if (e.impulsePercentage !== undefined) {
      parts.push(`impulse = ${fmt(e.impulsePercentage)}`);
      stats.zone++;
    }
    if (e.impulseAngle !== undefined) parts.push(`impulseAngle = ${fmt(e.impulseAngle)}`);
    if (e.impulseInward) parts.push("impulseInward = true");
    if (e.density !== undefined) parts.push(`density = ${fmt(e.density)}`);
    if (e.restitution !== undefined) parts.push(`restitution = ${fmt(e.restitution)}`);

    lua.push(`      { ${parts.join(", ")} },`);
  }
  lua.push("    },");

  if (L.joints && L.joints.length) {
    lua.push("    joints = {");
    for (const jt of L.joints) {
      const a = jt.jointAttributes || {};
      const p = [`a = "${jt.bodyId1}"`, `b = "${jt.bodyId2}"`,
                 `kind = "${(jt.type || "revolute").toLowerCase()}"`];
      if (a.enableMotor) p.push("motor = true");
      if (a.motorSpeed !== undefined) p.push(`motorSpeed = ${fmt(a.motorSpeed)}`);
      if (a.maxMotorTorque !== undefined) p.push(`maxMotorTorque = ${fmt(a.maxMotorTorque)}`);
      lua.push(`      { ${p.join(", ")} },`);
      stats.joints++;
    }
    lua.push("    },");
  }

  lua.push("  },");
});

lua.push("}");

const out = join(HERE, "..", "app", "levels.lua");
writeFileSync(out, lua.join("\n") + "\n");
console.log(`${out}: ${levels.length} holes`);
console.log(`  rect ${stats.rect}  circle ${stats.circle}  poly ${stats.poly}`);
console.log(`  water ${stats.water}  sand ${stats.sand}  impulse zones ${stats.zone}`);
console.log(`  joints ${stats.joints}`);
